add_rules("mode.debug", "mode.release")
add_requires("gtest")

target("libsocket")
	set_languages("c++17")
	set_kind("static")
	add_includedirs("include", {public = true})
	add_files("src/*.cpp|main.cpp")

target("test")
	set_languages("c++17")
	set_kind("binary")
	add_files("test/*.cpp")
	add_packages("gtest")
	add_deps("libsocket")
